package model;
// Generated 06-Aug-2018 19:42:17 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * AvioKompanije generated by hbm2java
 */
public class AvioKompanije  implements java.io.Serializable {


     private Integer idAvioKompanije;
     private String naziv;
     private Set<Destinacije> destinacijes = new HashSet<Destinacije>(0);

    public AvioKompanije() {
    }

    public AvioKompanije(String naziv, Set<Destinacije> destinacijes) {
       this.naziv = naziv;
       this.destinacijes = destinacijes;
    }
   
    public Integer getIdAvioKompanije() {
        return this.idAvioKompanije;
    }
    
    public void setIdAvioKompanije(Integer idAvioKompanije) {
        this.idAvioKompanije = idAvioKompanije;
    }
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }
    public Set<Destinacije> getDestinacijes() {
        return this.destinacijes;
    }
    
    public void setDestinacijes(Set<Destinacije> destinacijes) {
        this.destinacijes = destinacijes;
    }




}


