package model;
// Generated 06-Aug-2018 19:42:17 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Rezervacija generated by hbm2java
 */
public class Rezervacija  implements java.io.Serializable {


     private Integer idRezervacije;
     private Destinacije destinacije;
     private Hoteli hoteli;
     private Korisnici korisnici;
     private String datum;

    public Rezervacija() {
    }

    public Rezervacija(Destinacije destinacije, Hoteli hoteli, Korisnici korisnici, String datum) {
       this.destinacije = destinacije;
       this.hoteli = hoteli;
       this.korisnici = korisnici;
       this.datum = datum;
    }
   
    public Integer getIdRezervacije() {
        return this.idRezervacije;
    }
    
    public void setIdRezervacije(Integer idRezervacije) {
        this.idRezervacije = idRezervacije;
    }
    public Destinacije getDestinacije() {
        return this.destinacije;
    }
    
    public void setDestinacije(Destinacije destinacije) {
        this.destinacije = destinacije;
    }
    public Hoteli getHoteli() {
        return this.hoteli;
    }
    
    public void setHoteli(Hoteli hoteli) {
        this.hoteli = hoteli;
    }
    public Korisnici getKorisnici() {
        return this.korisnici;
    }
    
    public void setKorisnici(Korisnici korisnici) {
        this.korisnici = korisnici;
    }
    public String getDatum() {
        return this.datum;
    }
    
    public void setDatum(String datum) {
        this.datum = datum;
    }




}


