package model;
// Generated 06-Aug-2018 19:42:17 by Hibernate Tools 4.3.1



/**
 * Zaposleni generated by hbm2java
 */
public class Zaposleni  implements java.io.Serializable {


     private Integer idZaposleni;
     private String ime;
     private String username;
     private String password;

    public Zaposleni() {
    }

    public Zaposleni(String ime, String username, String password) {
       this.ime = ime;
       this.username = username;
       this.password = password;
    }
   
    public Integer getIdZaposleni() {
        return this.idZaposleni;
    }
    
    public void setIdZaposleni(Integer idZaposleni) {
        this.idZaposleni = idZaposleni;
    }
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


